/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.DireccionControlador;
import controlador.PaisControlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Direccion;

/**
 *
 * @author Asus
 */
public class DireccionVista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DireccionVista.class.getName());

    /**
     * Creates new form DireccionVista
     */
    public DireccionVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCiudad = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCalle = new javax.swing.JTextPane();
        btnCrear = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodPostal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLtitulo.setBackground(new java.awt.Color(204, 255, 255));
        LBLtitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBLtitulo.setText("INSERTE UN NUEVO PAIS");

        jScrollPane1.setViewportView(txtCiudad);

        jLabel2.setText("Ciudad:");

        jLabel3.setText("Calle:");

        jScrollPane2.setViewportView(txtCalle);

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        jLabel1.setText("Cod postal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBLtitulo)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCrear)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LBLtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnBorrar))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Direccion d = new Direccion();

    d.setCalle(txtCalle.getText());
    d.setCiudad(txtCiudad.getText());
    d.setCodPostal(Integer.parseInt(txtCodPostal.getText()));

    PaisControlador pc = new PaisControlador();

    ArrayList<String[]> lista = pc.obtenerPaises();

    String[] opciones = new String[lista.size()];

    for (int i = 0; i < lista.size(); i++) {
        opciones[i] = lista.get(i)[1];
    }

    String paisSeleccionado = (String) JOptionPane.showInputDialog(
            null,
            "Seleccione un país",
            "PAÍSES",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]);

    int idPais = -1;

    for (String[] pais : lista) {

        if (pais[1].equals(paisSeleccionado)) {

            idPais = Integer.parseInt(pais[0]);
            break;

        }

    }

    DireccionControlador dc = new DireccionControlador();
    dc.insertarDireccion(d, idPais);


    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
         DireccionControlador dc = new DireccionControlador();

    ArrayList<String[]> lista = dc.obtenerDirecciones();

    String[] opciones = new String[lista.size()];

    for (int i = 0; i < lista.size(); i++) {

        opciones[i] = lista.get(i)[1];

    }

    String direccionSeleccionada = (String) JOptionPane.showInputDialog(
            null,
            "Seleccione una dirección",
            "DIRECCIONES",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]);

    int idDireccion = -1;

    for (String[] dir : lista) {

        if (dir[1].equals(direccionSeleccionada)) {

            idDireccion = Integer.parseInt(dir[0]);
            break;

        }

    }

    dc.eliminarDireccion(idDireccion);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         DireccionControlador dc = new DireccionControlador();

    ArrayList<String[]> lista = dc.obtenerDirecciones();

    String[] opciones = new String[lista.size()];

    for (int i = 0; i < lista.size(); i++) {

        opciones[i] = lista.get(i)[1]; // calle

    }

    String direccionSeleccionada = (String) JOptionPane.showInputDialog(
            null,
            "Seleccione una dirección",
            "DIRECCIONES",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]);

    int idDireccion = -1;
    String calle = "";
    String ciudad = "";
    String codPostal = "";

    for (String[] dir : lista) {

        if (dir[1].equals(direccionSeleccionada)) {

            idDireccion = Integer.parseInt(dir[0]);
            calle = dir[1];
            ciudad = dir[2];
            codPostal = dir[3];

            break;

        }

    }

    EditarDireccionVista ed = new EditarDireccionVista();

    ed.setVisible(true);

    this.setVisible(false);

    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DireccionVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLtitulo;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtCalle;
    private javax.swing.JTextPane txtCiudad;
    private javax.swing.JTextField txtCodPostal;
    // End of variables declaration//GEN-END:variables
}
