/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PaisControlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Pais;

/**
 *
 * @author Asus
 */
public class PaisVista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaisVista.class.getName());

    /**
     * Creates new form PaisVista
     */
    public PaisVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLtitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCapital = new javax.swing.JTextPane();
        btnCrear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        bntPdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        LBLtitulo.setBackground(new java.awt.Color(204, 255, 255));
        LBLtitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBLtitulo.setText("INSERTE UN NUEVO PAIS");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Capital:");

        jScrollPane1.setViewportView(txtNombre);

        jScrollPane2.setViewportView(txtCapital);

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        bntPdf.setBackground(new java.awt.Color(255, 153, 153));
        bntPdf.setText("CREAR PDF");
        bntPdf.addActionListener(this::bntPdfActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBLtitulo)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntPdf)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LBLtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar)
                    .addComponent(bntPdf))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        Pais p = new Pais();
        
        p.setNombre(txtNombre.getText());
        p.setCapital(txtCapital.getText());
        PaisControlador pc = new PaisControlador();
        pc.insertarPais(p);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        Pais p = new Pais();
        
        PaisControlador deber = new PaisControlador();

        ArrayList<String[]> lista = deber.obtenerPaises();
        String[] identificadores = new String[lista.size()];
        String[] opciones = new String[lista.size()];

        for (int i = 0; i < lista.size(); i++) {
            opciones[i] = lista.get(i)[1]; // nombre del país
            identificadores[i] = lista.get(i)[0]; // id apis
        }
        for (String[] pais : lista) {
            System.out.println(
                    pais[1]
            );

        }
        String paisSeleccionado = (String) JOptionPane.showInputDialog(
                null,
                "Escoja su país",
                "PAÍSES",
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]);

        int idPais = -1;
        String capitalPais ="";
        for (String[] pais : lista) {
            if (pais[1].equals(paisSeleccionado)) {
                idPais = Integer.parseInt(pais[0]);
                capitalPais = pais[2]; // Este es el id REAL de la BD
                break;
            }
        }

        System.out.println("Id seleccionado: " + idPais);
        EditarPaisVista ep = new EditarPaisVista(idPais, paisSeleccionado, capitalPais);
        ep.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        Pais p = new Pais();
        
        PaisControlador deber = new PaisControlador();

        ArrayList<String[]> lista = deber.obtenerPaises();
        String[] identificadores = new String[lista.size()];
        String[] opciones = new String[lista.size()];

        for (int i = 0; i < lista.size(); i++) {
            opciones[i] = lista.get(i)[1]; // nombre del país
            identificadores[i] = lista.get(i)[0]; // id apis
        }
        for (String[] pais : lista) {
            System.out.println(
                    pais[1]
            );

        }
        String paisSeleccionado = (String) JOptionPane.showInputDialog(
                null,
                "Escoja su país",
                "PAÍSES",
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]);

        int idPais = -1;
        String capitalPais ="";
        for (String[] pais : lista) {
            if (pais[1].equals(paisSeleccionado)) {
                idPais = Integer.parseInt(pais[0]);
                capitalPais = pais[2]; // Este es el id REAL de la BD
                break;
            }
        }
        
        deber.eliminarPais(idPais);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void bntPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPdfActionPerformed
        // TODO add your handling code here:
        PaisControlador deber = new PaisControlador();
        deber.obtenerPaisesTodos();
    }//GEN-LAST:event_bntPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaisVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLtitulo;
    private javax.swing.JButton bntPdf;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtCapital;
    private javax.swing.JTextPane txtNombre;
    // End of variables declaration//GEN-END:variables
}
